# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-24 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0003_auto_20160924_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_manufct',
            field=models.CharField(default='Apple', max_length=255, verbose_name='メーカー'),
            preserve_default=False,
        ),
    ]
