# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-24 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0005_bihin_bihin_shisan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bihin',
            name='bihin_text',
            field=models.TextField(null=True, verbose_name='状態'),
        ),
    ]
