# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-24 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0007_auto_20160924_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_sts',
            field=models.IntegerField(choices=[(0, '保管棚'), (1, '貸出中'), (2, '廃棄')], default=0, verbose_name='状態'),
            preserve_default=False,
        ),
    ]
