# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0008_bihin_bihin_sts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_user',
            field=models.CharField(default=' ', max_length=255, verbose_name='使用者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bihin',
            name='bihin_date',
            field=models.DateField(help_text='<small><small>ex.) 2016-09-12</small></small>', verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='bihin',
            name='bihin_manufct',
            field=models.CharField(help_text='<small><small>ex.) Apple/DELL/lenovo</small></small>', max_length=255, verbose_name='メーカー'),
        ),
        migrations.AlterField(
            model_name='bihin',
            name='bihin_no',
            field=models.CharField(help_text='<small><small>ex.) JSL.NT.123456</small></small>', max_length=255, verbose_name='管理No'),
        ),
    ]
