# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0010_auto_20161016_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bihin',
            name='bihin_user',
            field=models.CharField(default='', max_length=255, verbose_name='使用者'),
            preserve_default=False,
        ),
    ]
