# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0012_auto_20161016_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_prj',
            field=models.CharField(blank=True, max_length=255, verbose_name='使用プロジェクト'),
        ),
        migrations.AlterField(
            model_name='bihin',
            name='bihin_no',
            field=models.CharField(help_text='<small><small>ex.) JSL.NT.123456</small></small>', max_length=255, unique=True, verbose_name='管理No'),
        ),
    ]
