# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0014_bihin_bihin_ipaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_cpu',
            field=models.CharField(default='Mac OS X', max_length=255, verbose_name='CPU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bihin',
            name='bihin_hdd',
            field=models.CharField(default='500GB', max_length=255, verbose_name='HDD容量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bihin',
            name='bihin_os',
            field=models.CharField(default='Mac OS X', max_length=255, verbose_name='OS'),
            preserve_default=False,
        ),
    ]
