# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0015_auto_20161016_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_mediadrv',
            field=models.CharField(blank=True, max_length=255, verbose_name='メディアドライブ'),
        ),
        migrations.AddField(
            model_name='bihin',
            name='bihin_mem',
            field=models.CharField(default='8GB', max_length=255, verbose_name='メモリ'),
            preserve_default=False,
        ),
    ]
