# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0016_auto_20161016_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_lease',
            field=models.DateField(blank=True, help_text='<small><small>ex.) 2016-09-12</small></small>', null=True, verbose_name='リース期限日'),
        ),
    ]
