# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0017_bihin_bihin_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_dispno',
            field=models.CharField(blank=True, max_length=255, verbose_name='付属品：ディスプレイ(管理No)'),
        ),
        migrations.AddField(
            model_name='bihin',
            name='bihin_dispsize',
            field=models.CharField(blank=True, max_length=255, verbose_name='付属品：ディスプレイ(size)'),
        ),
    ]
