# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bihin', '0018_auto_20161016_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bihin',
            name='bihin_keyno',
            field=models.CharField(blank=True, max_length=255, verbose_name='付属品：キーボード(管理No)'),
        ),
        migrations.AddField(
            model_name='bihin',
            name='bihin_mouseno',
            field=models.CharField(blank=True, max_length=255, verbose_name='付属品：マウス(管理No)'),
        ),
    ]
